import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
// import NavCart from "./components/NavCart/NavCart";
import { getDataProducts } from "@/sanity/lib/client";
import { getCategories } from "@/sanity/lib/client";
const inter = Inter({ subsets: ["latin"] });
export const dynamic = "force-dynamic";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // get all of our pages
  const products = await getDataProducts();
  const categories = await getCategories();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <Navbar />
          {/* <NavCart /> */}
          {/* MENU de products */}
          <div className="links">
            {products.map((product) => (
              <Link
                key={product._id}
                href={`/products/${product.slug}`}
                className="link"
              >
                {product.name}
              </Link>
            ))}
          </div>
          {/* /////// */}
          <div className="links">
            {categories.map((category) => (
              <Link
                key={category._id}
                href={`/categories/${category.slug}`}
                className="link"
              >
                {category.name}
              </Link>
            ))}
          </div>
        </header>
        <main className="main">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
