import { Inter } from "next/font/google";
import "./globals.css";
import { getPages } from "@/sanity/lib/client";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
export const dynamic = "force-dynamic";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <Link href="/" className="logo">
            LOGO
          </Link>
          <div className="links">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="link">
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
